views.area.niobi_research_center_department_add_button:
  type: views_area
  label: 'Department Add Button'
views.area.niobi_research_center_group_add_button:
  type: views_area
  label: 'Group Add Button'
views.field.niobi_research_center_department_add_button_field:
  type: views_field
  label: 'Department Add Button'
views.field.niobi_research_center_group_add_button_field:
  type: views_field
  label: 'Group Add Button'