# Modal Page Settings.
modal_page.settings:
  type: config_object
  label: 'Modal Page Settings'
  mapping:
    no_modal_page_external_js:
      type: boolean
      label: "Don't load external JS Bootstrap (bootstrap.min.js)"
