# Schema for configuration files of Form Mode Manager User roles assign module.
form_mode_user_roles_assign.settings:
  type: config_object
  label: 'Form Mode User Roles Auto Assign'
  mapping:
    form_modes:
      type: sequence
      label: 'Form mode to automatically assign user roles'
      sequence:
        type: mapping
        mapping:
          assign_roles:
            type: sequence
            label: 'List of roles to assign for this form mode'
            sequence:
              type: string
              label: 'Role name'
