# Schema for the configuration files of the group_flex module.

group.type.*.third_party.group_flex:
  type: mapping
  label: 'Group Flex settings'
  mapping:
    group_flex_enabler:
      type: 'boolean'
      label: 'Group Flex is enabled'
    group_type_visibility:
      type: 'string'
      label: 'Group type visibility'
    group_type_joining_method:
      type: 'sequence'
      label: 'Group joining methods'
      sequence:
        type: 'string'
        label: 'Group joining method'
    group_type_joining_method_override:
      type: 'boolean'
      label: 'Group owner can override the joining methods for their group'
