field.widget.settings.radiostoslider:
  type: mapping
  label: 'Radios to Slider widget settings'
  mapping:
    animation:
      type: boolean
      label: 'Enable animation'
    fit_container:
      type: boolean
      label: 'Fit container'
