# Schema for the configuration files of the agerp_core_basic module.

agerp_core_basic.type.*:
  type: config_entity
  label: 'Party type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Whether or not this type is locked.'
    primary_fields:
      type: sequence
      label: 'The fields the party uses primarily'
      sequence:
        type: string
        label: 'Field'


