id: entity_taxonomy_settings
label: entity_taxonomy configuration
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - entity_taxonomy_override_selector
    - entity_taxonomy_terms_per_page_admin
  source_module: entity_taxonomy
process:
  override_selector: entity_taxonomy_override_selector
  terms_per_page_admin: entity_taxonomy_terms_per_page_admin
destination:
  plugin: config
  config_name: entity_taxonomy.settings
