# Schema for the configuration files of the Maestro Engine module.

maestro.maestro_template.*:
  type: config_entity
  label: 'Maestro Template'
  mapping:
    id:
      type: string
      label: 'Template id'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Template Name'
    app_group:
      type: integer
      label: 'App Group'
    canvas_height:
      type: integer
      label: 'Canvas Height'
    canvas_width:
      type: integer
      label: 'Canvas Width'
    default_workflow_timeline_stage_count:
      type: integer
      label: 'Default workflow timeline stage count'
    show_details:
      type: boolean
      label: 'Show process details in task console'
    validated:
      type: boolean
      label: Validated
    views_attached:
      type: sequence
      label: 'Views Attached to Task Console Details'
      sequence:
        type: mapping
        label: 'View Attached'
        mapping:
          view_machine_name:
            type: string
            label: 'The View Machine Name'
          view_weight:
            type: integer
            label: 'Weight order of the view'
          view_display:
            type: string
            label: 'MachineName;Label of the display chosen for the view'
    variables:
      type: sequence
      label: 'Template Variables'
      sequence:
        type: mapping
        label: 'Variable'
        mapping:
          variable_id:
            type: string
            label: 'Template Machine Name'
          variable_value:
            type: text
            label: 'Variable Value'
    tasks:
      type: sequence
      label: 'Tasks'
      sequence:
        type: mapping
        label: 'Task Settings'
        mapping:
          id:
            type: string
            label: 'Machine Name'
          tasktype:
            type: string
            label: 'Task Type'
          label:
            type: string
            label: 'Task Name'
          nextstep:
            type: string
            label: 'Next Step'
          nextfalsestep:
            type: string
            label: 'Next False Step'
          runonce:
            type: boolean
            label: 'Run Once'
          top: 
            type: string
            label: 'Top of Task'
          left:
            type: string
            label: 'Left edge of Task'
          assignby:
            type: string
            label: 'variable or fixed value'
          assignto:
            type: string
            label: 'engine, user, role, group, etc.'
          assigned:
            type: string
            label: 'Assigned to'
          handler:
            type: string
            label: 'Execution Handler'
          showindetail:
            type: boolean
            label: 'Show in Detail Listings'
          participate_in_workflow_status_stage:
            type: boolean
            label: 'Particpate in setting the workflow stage and status'
          workflow_status_stage_number:
            type: integer
            label: 'Workflow Status Stage Number'
          workflow_status_stage_message:
            type: string
            label: 'Workflow Status Stage Message'
          data:
            type: maestro.task.[%parent.id]
          notifications:
            type: 'mapping'
            label: 'notifications'
            mapping:
              notification_assignment:
                type: string
                label: 'Custom Assignment Notification'
              notification_reminder:
                type: string
                label: 'Custom Reminder Notification'
              notification_escalation:
                type: string
                label: 'Custom Escalation Notification'
              escalation_after:
                type: integer
                label: 'Escalation after X days'
              reminder_after:
                type: integer
                label: 'Reminder after X days'
              assignment_enabled:
                type: boolean
                label: 'Assignment notification enabled'
              reminder_enabled:
                type: boolean
                label: 'Reminder notification enabled'
              escalation_enabled:
                type: boolean
                label: 'Reminder notification enabled'
              notification_assignments:
                type: string
                label: 'The csv of assignment settings. e.g. user:fixed:admin:assignment  entity:how:who:notification_type,...'  
        
maestro.task.*:
  type: mapping
  label: 'Maestro Task Data'
  
