# Schema for configuration files of Form Mode Manager Theme Switcher module.
form_mode_manager_theme_switcher.settings:
  type: config_object
  label: 'Form Mode Theme Switcher configuration object.'
  mapping:
    type:
      type: sequence
      label: 'The kind of theme type choose by admin.'
      sequence:
        type: string
        label: 'Name of theme configuration or custom if specific theme is needed.'
    form_mode:
      type: sequence
      label: 'Specific active theme.'
      sequence:
        type: string
        label: 'Name of specific theme to display if _custom type is set.'
