entity_collector.entity_collection_type.*:
  type: config_entity
  label: 'Entity collection type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    source:
      type: string
    source_field_name:
      type: string
