name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^9 || ^10
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2022-03-23
version: '1.0.0-beta6'
project: 'eca'
datestamp: 1648025783
