name: Buttons Configuration
type: module
description: "Allow users to change the text displayed on the content type or media type forms submit button."
core: 8.x
core_version_requirement: ^8 || ^9
configure: buttons_config.config.form
package: "Fields"

# Information added by Drupal.org packaging script on 2021-08-23
version: '1.0.0'
project: 'buttons_config'
datestamp: 1629728327
