settings:
  type: mapping
  label: "Social User Settigns"
  mapping:
    social_signup_help:
      type: text
      label: "Social Signup Help Text"
    social_login_help:
      type: text
      label: "Social Log in Help Text"
