language: node_js

sudo: false

node_js:
  - "node"

addons:
  apt:
    packages:
      - p7zip-full

env:
  global:
    - BASE_NAME=shariff-$TRAVIS_TAG

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run build_zip

deploy:
  - provider: releases
    api_key:
      secure: "QK+97CEzaL5FwA09hs7II9PnBKn1KRUUOLtmGnIw83FiqI5dUtAfPxe0WuA9dwIVX9FKOtPacn5nSoPb0LVvWwdTxGN2DOnYrUW8pIsPGng1Z5kbD2feJdTIeXkVmKb8JYssq76L7O6SyXQbkrbYq6KmrjFH9bEEpGlcUOyKY+k="
    file:
      - $BASE_NAME.zip
      - $BASE_NAME.tar.gz
    skip_cleanup: true
    on:
      repo: heiseonline/shariff
      tags: true
  - provider: npm
    email: npmjs@heise.de
    api_key:
      secure: "TukgzT1vc1Sli1cKVdVHdEen/89NqBDMgjSFe3iDr/oTulYE7sqR1JkdxX2M5lnCC53DqRnUK0mUs4mrWcZmHF+Q1ocVSuHDOi30iBvHQgV2SigV0Ufq3xwDG+yS4R7kPLEWlUVzn8kb6IXR+WC/QmkHWNRX6mkCnH0RjrqCja4="
    skip_cleanup: true
    on:
      repo: heiseonline/shariff
      tags: true
