block.settings.browser_back_button_block:
  type: block_settings
  label: 'Browser Back Button Block configuration'
  mapping:
    body:
      type: text_format
      label: 'Body'
    reload_status:
      type: boolean
      label: 'Reload Status'
