views.display.design:
  type: views_display
  label: 'Design display options'
  mapping:
    design:
      type: design_object

views.style.designs:
  type: views_style
  label: 'Design list'
  mapping:
    design:
      type: design_object

views.row.design:
  type: views_row
  label: 'Design options'
  mapping:
    design:
      type: design_object

views.display_extender.design:
  type: views_display_extender
