name: 'Tasks Kit'
type: module
description: 'Initial configuration to provide a system for user-defined tasks and a block to display them'
core_version_requirement: ^8 || ^9 || ^10
package: 'Configuration Kits'
dependencies:
  - drupal:link
  - drupal:user
  - add_content_by_bundle:add_content_by_bundle
  - display_link_plus:display_link_plus
  - draggableviews:draggableviews
  - storage:storage
  - flag:flag

# Information added by Drupal.org packaging script on 2022-08-19
version: '1.0.2'
project: 'tasks'
datestamp: 1660896547
