content_as_config.config:
  path: '/admin/structure/content-as-config'
  defaults:
    _form: '\Drupal\content_as_config\Form\SettingsForm'
    _title: 'Content as Config'
  requirements:
    _permission: 'administer site configuration'

content_as_config.taxonomies.export:
  path: '/admin/structure/content-as-config/taxonomies-export'
  defaults:
    _form: '\Drupal\content_as_config\Form\TaxonomiesExportForm'
    _title: 'Export taxonomies'
  requirements:
    _permission: 'administer site configuration'

content_as_config.taxonomies.import:
  path: '/admin/structure/content-as-config/taxonomies-import'
  defaults:
    _form: '\Drupal\content_as_config\Form\TaxonomiesImportForm'
    _title: 'Import taxonomies'
  requirements:
    _permission: 'administer site configuration'

content_as_config.blocks.export:
  path: '/admin/structure/content-as-config/blocks-export'
  defaults:
    _form: '\Drupal\content_as_config\Form\BlockContentExportForm'
    _title: 'Export blocks'
  requirements:
    _permission: 'administer site configuration'

content_as_config.blocks.import:
  path: '/admin/structure/content-as-config/blocks-import'
  defaults:
    _form: '\Drupal\content_as_config\Form\BlockContentImportForm'
    _title: 'Import blocks'
  requirements:
    _permission: 'administer site configuration'

content_as_config.menu.export:
  path: '/admin/structure/content-as-config/menu-export'
  defaults:
    _form: '\Drupal\content_as_config\Form\MenuLinksExportForm'
    _title: 'Export menu links'
  requirements:
    _permission: 'administer site configuration'

content_as_config.menu.import:
  path: '/admin/structure/content-as-config/menu-import'
  defaults:
    _form: '\Drupal\content_as_config\Form\MenuLinksImportForm'
    _title: 'Import menu links'
  requirements:
    _permission: 'administer site configuration'
