content_as_config.config:
  route_name: content_as_config.config
  title: Basic settings
  base_route: content_as_config
  weight: 0

content_as_config.taxonomies:
  route_name: content_as_config.taxonomies.export
  title: Taxonomies
  base_route: content_as_config
  weight: 10

content_as_config.taxonomies.export:
  title: Export
  route_name: content_as_config.taxonomies.export
  parent_id: content_as_config.taxonomies

content_as_config.taxonomies.import:
  title: Import
  route_name: content_as_config.taxonomies.import
  parent_id: content_as_config.taxonomies
  weight: 1

content_as_config.blocks:
  route_name: content_as_config.blocks.export
  title: Custom blocks
  base_route: content_as_config
  weight: 20

content_as_config.blocks.export:
  title: Export
  route_name: content_as_config.blocks.export
  parent_id: content_as_config.blocks

content_as_config.blocks.import:
  title: Import
  route_name: content_as_config.blocks.import
  parent_id: content_as_config.blocks
  weight: 1

content_as_config.menu:
  route_name: content_as_config.menu.export
  title: Menu links
  base_route: content_as_config
  weight: 30

content_as_config.menu.export:
  title: Export
  route_name: content_as_config.menu.export
  parent_id: content_as_config.menu

content_as_config.menu.import:
  title: Import
  route_name: content_as_config.menu.import
  parent_id: content_as_config.menu
  weight: 1
