entity.config_terms_vocab.add_form:
  route_name: 'entity.config_terms_vocab.add_form'
  title: 'Add Config terms vocab'
  appears_on:
    - entity.config_terms_vocab.collection
entity.config_terms_term.add_form:
  route_name: 'entity.config_terms_term.add_form'
  title: 'Add Config terms term'
  appears_on:
    - entity.config_terms_vocab.overview_form
