drupal.taxonomy:
  version: VERSION
  js:
    config_terms.js: {}
  css:
    component:
      css/config_terms.theme.css: {}
  dependencies:
    - core/jquery
    - core/drupal
    - core/drupalSettings
    - core/drupal.tabledrag
