entity.config_terms_term.edit_form:
  title: Edit
  group: config_terms_term
  route_name: entity.config_terms_term.edit_form
  weight: 10

entity.config_terms_term.delete_form:
  title: Delete
  group: config_terms_term
  route_name: entity.config_terms_term.delete_form
  weight: 20

entity.config_terms_vocab.delete_form:
  title: Delete
  group: config_terms_vocab
  route_name: entity.config_terms_vocab.delete_form
  weight: 20
