entity.config_terms_vocab.collection:
  path: '/admin/structure/config-terms'
  defaults:
    _entity_list: 'config_terms_vocab'
    _title: 'Config terms vocabularies'
  requirements:
    _permission: 'administer config_terms'

entity.config_terms_term.add_form:
  path: '/admin/structure/config-terms/{config_terms_vocab}/add'
  defaults:
    _controller: '\Drupal\config_terms\Controller\ConfigTermsController::addForm'
    _title: 'Add config term'
  requirements:
    _entity_create_access: 'config_terms_term:{config_terms_vocab}'

entity.config_terms_term.edit_form:
  path: '/config-terms/config-term/{config_terms_term}/edit'
  defaults:
    _entity_form: 'config_terms_term.default'
    _title: 'Edit config term'
  options:
    _admin_route: TRUE
  requirements:
    _entity_access: 'config_terms_term.update'

entity.config_terms_term.delete_form:
  path: '/config-terms/term/{config_terms_term}/delete'
  defaults:
    _entity_form: 'config_terms_term.delete'
    _title: 'Delete config term'
  options:
    _admin_route: TRUE
  requirements:
    _entity_access: 'config_terms_term.delete'

entity.config_terms_vocab.add_form:
  path: '/admin/structure/config-terms/add'
  defaults:
    _entity_form: 'config_terms_vocab'
    _title: 'Add config terms vocab'
  requirements:
    _entity_create_access: 'config_terms_vocab'

entity.config_terms_vocab.edit_form:
  path: '/admin/structure/config-terms/{config_terms_vocab}/edit'
  defaults:
    _entity_form: 'config_terms_vocab.default'
    _title_callback: '\Drupal\config_terms\Controller\ConfigTermsController::vocabTitle'
  requirements:
    _entity_access: 'config_terms_vocab.update'

entity.config_terms_vocab.delete_form:
  path: '/admin/structure/config-terms/{config_terms_vocab}/delete'
  defaults:
    _entity_form: 'config_terms_vocab.delete'
    _title: 'Delete config terms vocab'
  requirements:
    _entity_access: 'config_terms_vocab.delete'

entity.config_terms_vocab.reset_form:
  path: '/admin/structure/config-terms/{config_terms_vocab}/reset'
  defaults:
    _entity_form: 'config_terms_vocab.reset'
    _title: 'Reset'
  requirements:
    _permission: 'administer config_terms'

entity.config_terms_vocab.overview_form:
  path: '/admin/structure/config-terms/{config_terms_vocab}/overview'
  defaults:
    _form: 'Drupal\config_terms\Form\OverviewTerms'
    _title_callback: 'Drupal\config_terms\Controller\ConfigTermsController::vocabTitle'
  requirements:
    _entity_access: 'config_terms_vocab.view'
  options:
      parameters:
        config_terms_vocab:
          type: 'entity:config_terms_vocab'
