name: Config Terms
type: module
description: "Allows the creation of Config Entity based terms."
core_version_requirement: ^8.7.12 || ^9.0
package: Utility

# Information added by Drupal.org packaging script on 2021-04-01
version: '8.x-1.4'
project: 'config_terms'
datestamp: 1617247084
