entity.config_terms_vocab.overview_form:
  title: 'List'
  route_name: entity.config_terms_vocab.overview_form
  base_route: entity.config_terms_vocab.overview_form

entity.config_terms_vocab.edit_form:
  title: 'Edit'
  route_name: entity.config_terms_vocab.edit_form
  base_route: entity.config_terms_vocab.overview_form
