# Schema for the configuration files of the config_terms module.
config_terms.settings:
  type: config_object
  label: 'Config terms settings'
  mapping:
    maintain_index_table:
      type: boolean
      label: 'Maintain index table'
    override_selector:
      type: boolean
      label: 'Override selector'
    terms_per_page_admin:
      type: integer
      label: 'Number of terms per page'

config_terms.config_terms_vocab.*:
  type: config_entity
  label: 'Config terms vocab'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine name'
    description:
      type: label
      label: 'Description'
    weight:
      type: integer
      label: 'Weight'
    hierarchy:
      type: integer
      label: 'Hierarchy Type'
    term_id_prefix:
      type: string
      label: 'Term ID Prefix'

config_terms.config_terms_term.*:
  type: config_entity
  label: 'Config term config'
  mapping:
    id:
      type: string
      label: 'Machine name'
    vid:
      type: string
      label: 'VID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    parents:
      type: sequence
      label: 'parents'
      sequence:
        type: string
    weight:
      type: integer
      label: 'Weight'
    description:
      type: string
      label: 'Description'

field.formatter.settings.entity_reference_rss_category:
  type: mapping
  label: 'Config terms vocab format settings'

entity_reference_selection.default:config_terms_term:
  type: entity_reference_selection
  mapping:
    target_vocab:
      type: string
      label: 'Entity reference selection handler target config terms vocab'
    target_bundles:
      type: sequence
      label: 'types'
      nullable: true
      sequence:
        type: string
        label: 'Bundle'
    auto_create:
      type: boolean
      label: 'Create referenced entities if they don''t already exist'
