config_perms.custom_perms_entity.*:
  type: config_entity
  label: 'Custom perms entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    path:
      type: string
      label: 'path'
    status:
      type: boolean
      label: 'status'
    uuid:
      type: string
