lrn.settings:
  type: config_object
  label: 'LRN settings'
  mapping:
    firstname_field:
      type: string
      label: 'Fieldname for firstname'
    lastname_field:
      type: string
      label: 'Fieldname for lastname'
    middlename_field:
      type: string
      label: 'Fieldname for middlename'
    build_string:
      type: string
      label: 'Build string'
    allow_numbering:
      type: boolean
      label: 'Allow numbering homonyms'
    max_numbering:
      type: integer
      label: 'Max number for homonyms'
    fn_lowup:
      type: integer
      label: 'Firstname low/uppercase treatment'
    ln_lowup:
      type: integer
      label: 'Lastname low/uppercase treatment'
    mn_lowup:
      type: integer
      label: 'Middlename low/uppercase treatment'
    fn_change:
      type: integer
      label: 'Firstname rewrite rule'
    ln_change:
      type: integer
      label: 'Lastname rewrite rule'
    mn_change:
      type: integer
      label: 'Middlename rewrite rule'
    fn_max:
      type: integer
      label: 'Firstname max length'
    fn_translit:
      type: boolean
      label: 'Transliterate firstname to ASCII'
    ln_translit:
      type: boolean
      label: 'Transliterate lastname to ASCII'
    mn_translit:
      type: boolean
      label: 'Transliterate middlename to ASCII'
    ln_max:
      type: integer
      label: 'Lastname max length'
    mn_max:
      type: integer
      label: 'Middlename max length'
    full_max:
      type: integer
      label: 'Final max length'

