smart_content.reaction:
  type: config_object
  label: 'Reaction settings'
  mapping:
    id:
      type: string
      label: 'ID'
    plugin_id:
      type: string
      label: 'Plugin ID'
    weight:
      type: integer
      label: 'Reaction Weight'

smart_content.reaction.plugin.*:
  type: smart_content.reaction
