smart_content.variation_set_type:
  type: config_object
  label: 'Varation Set Type settings'
  mapping:
    plugin_id:
      type: string
      label: 'Plugin ID'

smart_content.variation_set_type.plugin.*:
  type: smart_content.variation_set_type
