smart_content.variation.plugin.variation_block:
  type: smart_content.variation
  mapping:
    conditions_settings:
      type: sequence
      label: 'Array of conditions with settings.'
      sequence:
        type: 'smart_content.condition.plugin.[type]'
    reactions_settings:
      type: sequence
      label: 'Array of reactions with settings'
      sequence:
        type: 'smart_content.reaction.plugin.[plugin_id]'
