field.value.friggeri_cv_profile_contact_box:
  type: mapping
  label: 'Profile Contact Box'
  mapping:
    heading:
      type: string
      label: 'Contact heading'
    font_awesome_icon:
      type: string
      label: 'Font Awesome icon'
    contacts:
      type: string
      label: 'Contact details'

field.value.friggeri_cv_profile_entity_box:
  type: mapping
  label: 'Profile Entity Box'
  mapping:
    tenure:
      type: string
      label: 'Tenure'
    title:
      type: string
      label: 'Title'
    employer:
      type: string
      label: 'Employer or Institution'
    domain:
      type: string
      label: 'Domain or subject'
    info:
      type: string
      label: 'Additional information'
