collection.collection_type.*:
  type: config_entity
  label: 'Collection type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    allowed_collection_item_types:
      type: sequence
      label: 'Allowed collection item types'
      nullable: true
      sequence:
        type: string
        label: 'Bundle'
    uuid:
      type: string

collection.collection_item_type.*:
  type: config_entity
  label: 'Collection item type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    allowed_bundles:
      type: sequence
      label: 'Allowed content entity bundles'
      nullable: true
      sequence:
        type: string
        label: 'Bundle'
    attributes_access:
      type: string

views.field.collection_view_item_entity_type_label:
  type: views_field
  label: 'The collected item type label'

views.field.collection_view_item_status:
  type: views_field
  label: 'The item entity status'
