ultimenu.settings:
  type: config_object
  label: 'Ultimenu settings'
  mapping:
    blocks:
      type: sequence
      label: 'Ultimenu blocks'
      sequence:
        - type: string
          label: Block
    regions:
      type: sequence
      label: 'Ultimenu regions'
      sequence:
        - type: string
          label: region
    skins:
      type: string
      label: 'Path to custom Ultimenu skins library'
    fallback_text:
      type: string
      label: 'Fallback text displayed as an AJAX link.'
    goodies:
      type: sequence
      label: 'Ultimenu goodies'
      sequence:
        - type: string
          label: goodies

block.settings.ultimenu_block:*:
  type: block_settings
  label: 'Ultimenu block'
  mapping:
    ajaxify:
      type: boolean
      label: Ajaxify
    regions:
      type: sequence
      label: 'Ajaxified regions'
      sequence:
        - type: string
          label: region
    skin:
      type: string
      label: 'Ultimenu skin'
    orientation:
      type: string
      label: 'Flyout orientation'
    submenu:
      type: boolean
      label: 'Render submenu'
    submenu_position:
      type: string
      label: 'Submenu position'
    canvas_off:
      type: string
      label: 'Off-canvas element'
    canvas_on:
      type: string
      label: 'On-canvas elements'
    canvas_skin:
      type: string
      label: 'Off-canvas skin'
