feeds_as_config.feeds:
  route_name: feeds_as_config.feeds.export
  title: Feeds
  base_route: content_as_config
  weight: 40

feeds_as_config.feeds.export:
  title: Export
  route_name: feeds_as_config.feeds.export
  parent_id: feeds_as_config.feeds

feeds_as_config.feed.import:
  title: Import
  route_name: feeds_as_config.feeds.import
  parent_id: feeds_as_config.feeds
  weight: 1
