feeds_as_config.feeds.export:
  path: '/admin/structure/content-as-config/feeds-export'
  defaults:
    _form: '\Drupal\feeds_as_config\Form\FeedsExportForm'
    _title: 'Export feeds'
  requirements:
    _permission: 'administer site configuration'

feeds_as_config.feeds.import:
  path: '/admin/structure/content-as-config/feeds-import'
  defaults:
    _form: '\Drupal\feeds_as_config\Form\FeedsImportForm'
    _title: 'Import feeds'
  requirements:
    _permission: 'administer site configuration'
