entity_ui.entity_tab.*.*:
  type: config_entity
  label: 'Entity tab config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    label:
      type: label
      label: 'The human-readable name of the entity tab. Used in admin listings.'
    path:
      type: path
      label: 'The path component for the tab.'
    tab_title:
      type: label
      label: 'The title of the tab on the target entity.'
    page_title:
      type: label
      label: 'The page title of the tab page.'
    target_entity_type:
      type: string
      label: 'Target entity type'
    target_bundles:
      type: sequence
      label: 'Target bundles'
      nullable: true
      sequence:
        type: string
        label: 'Bundle'
    content_plugin:
      type: string
      label: 'ID of the Entity Tab Content plugin'
    content_config:
      type: entity_ui.content_config.plugin.[%parent.content_plugin]
      label: 'Content configuration'
    weight:
      type: integer
      label: 'Weight'

# Schema for entity tab content plugins.
entity_ui.content_config.plugin.*:
  type: mapping
  label: 'Content configuration'

entity_ui.content_config.plugin.entity_view:
  type: mapping
  label: 'Content configuration'
  mapping:
    view_mode:
      type: string
      label: 'View mode'

entity_ui.content_config.plugin.entity_form:
  type: mapping
  label: 'Content configuration'
  mapping:
    form_mode:
      type: string
      label: 'Form mode'
