designs_field_object:
  type: mapping
  label: Designs field module support
  mapping:
    field_enabled:
      type: boolean
      label: Flag for use of the field wrapper
    field:
      type: design_object
      label: Designs field wrapper
    item_enabled:
      type: boolean
      label: Flag for use of the item wrapper
    item:
      type: design_object
      label: Designs item widget wrapper

field.widget.third_party.designs_field:
  type: designs_field_object
  label: Designs field module support

field.formatter.third_party.designs_field:
  type: designs_field_object
  label: Designs field module support
