system_tags.system_tag.*:
  type: config_entity
  label: 'System Tag config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
