settings:
  type: mapping
  label: "Social User Settings"
  mapping:
    signup_help:
      type: text
      label: "Signup Help Text"
    login_help:
      type: text
      label: "Log in Help Text"
    social_user_profile_landingpage:
      type: string
      label: "A valid route name that is used as default user profile page"
