settings:
  type: mapping
  label: "Social User Settigns"
  mapping:
    signup_help:
      type: text
      label: "Signup Help Text"
    login_help:
      type: text
      label: "Log in Help Text"
