social_tagging.settings:
  type: config_object
  label: 'Social Tagging Settings'
  mapping:
    enable_content_tagging:
      type: boolean
      label: 'Determines whether content tagging is enabled for users.'
    allow_category_split:
      type: boolean
      label: 'Determines whether the top level taxonomy items are considered categories for tagging.'
    tag_node_type_landing_page:
      type: boolean
      label: 'Determines whether the landing page node type has tagging enabled.'
