digsig_computed_content.digsig_computed_content_type.*:
  type: config_entity
  label: 'Computed content type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
