dfinance.financial_doc_type.*:
  type: config_entity
  label: 'Financial Document type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
    uuid:
      type: string
