dfinance.financial_account_code_type.*:
  type: config_entity
  label: 'Account Code type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
