clever_theme_switcher.cts.*:
  type: config_entity
  label: 'Clever Theme Switcher config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Name'
    theme:
      type: string
      label: 'Theme name'
    pages:
      type: text
      label: 'Pages'
    status:
      type: boolean
      label: 'Status'
    condition_collection:
      type: sequence
      label: 'Conditions'
      sequence:
        - type: condition.plugin
          label: 'Condition'
