views.area.display_link_plus:
  type: views_area
  label: 'Display Link Plus'
  mapping:
    display_id:
      type: string
      label: 'The id of the display that will be linked to.'
    label:
      type: label
      label: 'The label of the link.'
    class:
      type: string
      label: 'A CSS class to use on the link.'
    target:
      type: string
      label: 'Option to target a modal or off-screen dialog.'
    width:
      type: integer
      label: 'Width to use for the dialog.'
