digital_signage_framework:
  type: mapping
  label: 'Digital signage'
  mapping:
    cron_sync_devices:
      type: boolean
      label: 'Sync devices during cron'
    cron_sync_schedules:
      type: boolean
      label: 'Sync schedules during cron'
    plantuml_url:
      type: string
      label: 'PlantUML server url'
    css:
      type: string
      label: 'CSS files'
    fonts:
      type: string
      label: 'Font definitions'
    http_header:
      type: string
      label: 'HTTP request header'
    schedule:
      type: mapping
      label: 'Schedule generator default values'
      mapping:
        duration:
          type: int
          label: 'Duration'
        offsets:
          type: mapping
          label: 'Offset factors'
          mapping:
            complex:
              type: int
              label: 'Complex factor'
            critical:
              type: int
              label: 'Critical factor'
        priority_weight:
          type: mapping
          label: 'Priority factors'
          mapping:
            high:
              type: int
              label: 'High priority factor'
            normal:
              type: int
              label: 'Normal priority factor'
            low:
              type: int
              label: 'Low priority factor'
