digital_signage_device.digital_signage_device_type.*:
  type: config_entity
  label: 'Device type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

condition.plugin.digital_signage_device_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
