ala.settings:
  type: config_object
  label: 'Advance Link Attributes Settings'
  mapping:
    ala_default_classes:
      type: text
      label: 'Define possibles classes'

field.widget.settings.ala_field_widget:
  type: mapping
  label: 'Advance Link Attribute type widget settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
    ala_link_class_settings:
      type: string
      label: 'Class Settings'
    ala_link_class:
      type: string
      label: 'Define possibles classes'
    ala_link_icon:
      type: boolean
      label: 'Enable Icon'
    ala_link_roles:
      type: boolean
      label: 'Enable User Roles'
    ala_enable_target:
      type: boolean
      label: 'Enable Target'
    ala_link_color:
      type: boolean
      label: 'Enable Custom BG & Color'
field.formatter.settings.ala_field_widget:
  type: mapping
  label: 'Advance Link Attributes format settings'
  mapping:
    trim_length:
      type: integer
      label: 'Trim link text length'
    url_only:
      type: boolean
      label: 'URL only'
    url_plain:
      type: boolean
      label: 'Show URL as plain text'
    rel:
      type: string
      label: 'Add rel="nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'
    ala_link_view_class:
      type: string
      label: 'Class Position'
    ala_link_view_icon:
      type: string
      label: 'Icon Position'
    ala_link_view_roles:
      type: string
      label: 'Role Visibility'
