# Schema for the configuration files of the nbox module.
nbox.settings:
  type: config_object
  label: 'Nbox settings'
  mapping:
    reply_has_subject:
      type: boolean
      label: 'If the reply should also have a subject field'
    message_has_avatar:
      type: boolean
      label: 'If avatars should be shown in the message thread'
    message_avatar_style:
      type: string
      label: 'The image style to use when displaying avatars in messages'
    date_today:
      type: string
      label: 'The date format to use when a thread was last updated today'
    date_other:
      type: string
      label: 'The date format to use when a thread was last updated not today'

nbox.nbox_type.*:
  type: config_entity
  label: 'Nbox type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

# Schema for the configuration of the Recipient field type.
field.storage_settings.recipient:
  type: mapping
  label: 'Recipient field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.field_settings.recipient:
  type: mapping
  label: 'Recipient field settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.nbox:user
      label: 'Recipient selection plugin settings'

field.value.recipient:
  type: mapping
  label: 'Default value'
  mapping:
    target_id:
      type: string
      label: 'Value'
    target_uuid:
      type: uuid

# Field formatter.
field.formatter.settings.recipient_label:
  type: mapping
  label: 'Recipient label display format settings'
  mapping:
    link:
      type: boolean
      label: 'Link label to the referenced entity'

# Field widget.
field.widget.settings.recipient_autocomplete_tags:
  type: mapping
  label: 'Recipient autocomplete (Tags style) display format settings'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'

entity_reference_selection.nbox:user:
  type: entity_reference_selection
  label: 'Default selection handler settings'
  mapping:
    target_bundles:
      type: sequence
      label: 'types'
      nullable: true
      sequence:
        type: string
        label: 'Bundle'
    sort:
      type: mapping
      label: 'Sort settings'
      mapping:
        field:
          type: string
          label: 'Sort by'
        direction:
          type: string
          label: 'Sort direction'
    filter:
      type: mapping
      label: 'Filter settings'
      mapping:
        type:
          type: string
          label: 'Filter by'
    recipient_type:
      type: string
      label: 'Type of recipient'
    include_anonymous:
      type: integer
      label: 'Include the anonymous user in the matched entities.'
    auto_create:
      type: integer
      label: 'Create referenced entities if they don''t already exist'
