# Schema for the configuration files of the field_suggestion module.

field_suggestion.settings:
  type: config_object
  label: 'Field Suggestion settings'
  mapping:
    limit:
      type: integer
      label: 'The number of displayed values in a list of suggestions.'
    fields:
      type: sequence
      label: 'Fields split by entity types'
      sequence:
        type: sequence
        label: 'Entity type IDs'
        sequence:
          type: string
          label: 'Fields per entity type'
