# Schema for the configuration files of the Entity version workflows module.

workflows.workflow.*.third_party.entity_version_workflows:
  type: sequence
  label: 'Transition ID'
  sequence:
    type: mapping
    label: 'Transition actions'
    mapping:
      major:
        type: string
        label: 'Major action'
      minor:
        type: string
        label: 'Minor action'
      patch:
        type: string
        label: 'Patch action'
      check_values_changed:
        type: boolean
        label: 'Check values changed'
