field.field.*.*.*.third_party.disable_field:
  type: mapping
  label: 'Per-field disable_field settings'
  mapping:
    add_disable:
        type: string
        label: 'Option to disable field on the content add form'
    add_disable_roles:
      type: sequence
      label: 'Disable the field for the given roles on the content add form.'
      sequence:
        type: string
        label: 'Role'
    add_enable_roles:
      type: sequence
      label: 'Enable the field for the given roles on the content add form.'
      sequence:
        type: string
        label: 'Role'
    edit_disable:
      type: string
      label: 'Option to disable field on the content edit form'
    edit_disable_roles:
      type: sequence
      label: 'Disable the field for the given roles on the content edit form.'
      sequence:
        type: string
        label: 'Role'
    edit_enable_roles:
      type: sequence
      label: 'Enable the field for the given roles on the content edit form.'
      sequence:
        type: string
        label: 'Role'
