
freelinking_plugin:
  type: mapping
  mapping:
    plugin:
      type: string
      label: 'Plugin'
    enabled:
      type: boolean
      label: 'Status'
    settings:
      type: freelinking_settings.[%parent.plugin]
      label: 'Plugin Settings'

freelinking_settings.*:
  type: sequence
  sequence:
    type: string
    label: 'Value'

freelinking_settings.nodetitle:
  type: mapping
  mapping:
    nodetypes:
      type: sequence
      label: 'Content types'
      sequence:
        type: string
        label: 'Content type'
    failover:
      type: string
      label: 'Failover option'

filter_settings.freelinking:
  type: filter
  label: 'Freelinking'
  mapping:
    plugins:
      type: sequence
      label: 'Plugins'
      sequence:
        type: freelinking_plugin
    default:
      type: string
    global_options:
      type: mapping
      label: 'Global options'
      mapping:
        ignore_upi:
          type: boolean
          label: 'Ignore UPI'
          description: 'Ignore unknown plugin indicators.'
