# Schema for the configuration files of the transaction workflow module.

transaction.type.*.third_party.transaction_workflow:
  type: mapping
  label: 'Workflow transaction type settings'
  mapping:
    states:
      type: sequence
      label: 'Workflow states'
      sequence:
        type: label
        label: 'State label'
